from pathlib import Path
import json,pandas as pd,hashlib,datetime,time,sys
B=Path(__file__).resolve().parents[1];R=B/'results'
for p in [R/'identity_boundary_verification.json',R/'harmonization_audit.json']:
 while not p.exists():time.sleep(5)
a=json.loads((R/'whole_file_audit.json').read_text());h=json.loads((R/'harmonization_audit.json').read_text());num=json.loads((R/'numeric_range_audit.json').read_text());v=json.loads((R/'variant_manifest_audit.json').read_text());ids=json.loads((R/'identity_boundary_verification.json').read_text());src=json.loads((B/'sources/acquisition.json').read_text());vs=json.loads((B/'sources/variant_manifest.acquisition.json').read_text());l=pd.read_csv(R/'loci.tsv',sep='\t');d=pd.read_csv(R/'locus_variants.tsv.gz',sep='\t',keep_default_na=False);rec=[]
for q in l.to_dict('records'):
 g=d[d.locus_id==q['locus_id']];
 sig=pd.to_numeric(g.neglog10_p,errors='coerce')>7.301029995663981
 sg=g[sig&(g.qc_status=='SOURCE_STATISTIC_QC_PASS')];lead=g[g.source_row==q['lead_source_row']].iloc[0]
 rec.append({**q,**next(x for x in h['per_locus'] if x['locus_id']==q['locus_id']), 'all_significant_source_rows_signed_direction_verified':bool((sg.direction_status=='VERIFIED_SIGNED_GWAS_CONTRAST').all()),'significant_source_rows_with_provider_high_quality_false':int((sg.variant_qc_annotation=='PROVIDER_HIGH_QUALITY_FALSE_OR_MISSING').sum()),'lead_variant_qc_annotation':lead.variant_qc_annotation,'lead_harmonization_status':lead.harmonization_status,'signed_source_contrast_gate':'VERIFIED','RSS_sample_statistic_contract':'UNRESOLVED_SPA_SE_AND_PER_VARIANT_N_REFERENCE_RELATIONSHIP','LD_gate':'OWNED_BY_ROOT_SEPARATE_LD_AUDIT','execution_cleared_by_this_audit':False})
pd.DataFrame(rec).to_csv(R/'locus_gwas_gate_audit.tsv',sep='\t',index=False)
pd.DataFrame([{'field':c,'missing_rows':a['missingness'][c],'defined_rows':a['rows']-a['missingness'][c],'used_for_EUR_association':c in ['beta_EUR','se_EUR','neglog10_pval_EUR','af_cases_EUR','af_controls_EUR','low_confidence_EUR']} for c in a['header']]).to_csv(R/'whole_file_schema_missingness.tsv',sep='\t',index=False)
pd.DataFrame([{'track':'C','artifact':'GWAS','url':src['url'],'access_started_utc':src['started_utc'],'access_finished_utc':src['finished_utc'],'bytes':src['actual_bytes'],'sha256':src['sha256'],'md5':src['md5'],'provider_md5_matches':src['integrity_pass'],'complete_rows':a['rows'],'gzip_crc_pass':True},{'track':'C','artifact':'VARIANT_QC_DEPENDENCY','url':vs['url'],'access_started_utc':vs['started_utc'],'access_finished_utc':vs['finished_utc'],'bytes':vs['bytes'],'sha256':vs['sha256'],'md5':vs['md5'],'provider_md5_matches':vs['integrity_pass'],'complete_rows':v['rows'],'gzip_crc_pass':True}]).to_csv(R/'complete_file_integrity.tsv',sep='\t',index=False)
pd.DataFrame([{'chromosome':c,'rows':n} for c,n in a['chromosome_rows'].items()]).to_csv(R/'chromosome_coverage.tsv',sep='\t',index=False)
pd.DataFrame([{'stratum':k,**val} for k,val in a['wald_by_chrom_pband'].items()]).to_csv(R/'effect_test_consistency.tsv',sep='\t',index=False)
summary={'track':'C','scope_status':'GWAS_INPUT_AUDIT_COMPLETE','final_track_readiness':'Not assigned in this subaudit; root integrates separate LD and sampling-model gates','source':'Pan-UKB icd10 J44 both_sexes EUR','phenotype_role':'Secondary EHR/ICD sensitivity','complete_gwas_rows':a['rows'],'complete_file_integrity_pass':src['integrity_pass'] and a['gzip_complete_decode_crc_pass'] and a['row_count_matches_provider'],'valid_signed_rows':a['counts']['valid_signed_rows'],'source_qc_pass_autosomal_rows':a['counts']['valid_signed_autosomal_low_confidence_false_rows'],'prospective_merged_loci':len(l),'prospective_non_MHC_loci':int((l.locus_status!='DEFERRED_MHC').sum()),'MHC_deferred_loci':int((l.locus_status=='DEFERRED_MHC').sum()),'significant_source_seed_rows':a['counts']['genomewide_significant_seed_rows'],'prospective_locus_rows_including_MHC':len(d),'source_exact_duplicate_rows':ids['total_duplicate_identity_rows'],'normalized_locus_collision_rows':h['normalized_duplicate_rows'],'signed_direction_assigned_locus_rows':h['direction_status']['VERIFIED_SIGNED_GWAS_CONTRAST'],'all_GWAS_locus_REF_alleles_reference_match':len(d)==h['reference_match_counts'].get('true',0),'all_valid_EUR_rows_rounding_consistent_with_beta_over_se_P':a['counts']['wald_rounding_discrepant_valid_rows']==0,'rounding_consistency_interpretation':'Arithmetic consistency only; SAIGE0.36.3 derives SE from beta and SPA P; does not independently validate unadjusted likelihood covariance','single_nonmissing_invalid_row_preserved':'results/whole_file_invalid_numeric_rows.tsv','N_contract':'GWAS phenotype420531; per-variant GWAS N absent; variant-manifest AN/2 broader sample458317-458937; LD actual420542. No automatic N substitution.','test_contract':'ALT signed beta with SPA-calibrated SE and source SPA P; z=beta/se as supplied, no P-derived replacement','future_statistical_fine_mapping_performed':False,'statistical_execution_authorized_by_this_audit':False,'firewall':{'other_ancestry_or_meta_statistics_analyzed':False,'functional_gene_or_candidate_annotations_used':False,'LD_downloads_or_construction_by_track_C_agent':False,'prior_stage_modifications':False},'completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
(R/'audit.json').write_text(json.dumps(summary,indent=2)+'\n')
print(json.dumps(summary,indent=2),flush=True)
