from pathlib import Path
import pandas as pd,numpy as np,pysam,json,hashlib,datetime
B=Path(__file__).resolve().parents[1];R=B/'results';d=pd.read_csv(R/'locus_variants.tsv.gz',sep='\t',keep_default_na=False);l=pd.read_csv(R/'loci.tsv',sep='\t',dtype={'chrom':str});s=pd.read_csv(R/'gwas_significant_seeds.tsv',sep='\t',dtype={'chrom':str});risk=pd.read_csv(R/'risk_direction.tsv.gz',sep='\t',keep_default_na=False);fa=pysam.FastaFile(str(B.parents[1]/'references/GRCh37.p13.genome.fa'));checks=[]
def check(name,condition):
 checks.append({'check':name,'pass':bool(condition)});assert condition,name
check('all_locus_rows_present',len(d)==259252);check('risk_table_preserves_all_rows',len(risk)==len(d));check('no_native_exact_duplicates',not d.duplicated(['locus_id','variant_id']).any());check('all_reference_checks_pass',d.reference_match.all());check('all_original_beta_strings_preserved_numerically',np.allclose(pd.to_numeric(d.beta,errors='coerce'),pd.to_numeric(d.original_beta_EUR,errors='coerce'),equal_nan=True));check('all_original_SE_strings_preserved_numerically',np.allclose(pd.to_numeric(d.se,errors='coerce'),pd.to_numeric(d.original_se_EUR,errors='coerce'),equal_nan=True));b=pd.to_numeric(d.beta,errors='coerce');se=pd.to_numeric(d.se,errors='coerce');z=pd.to_numeric(d.z,errors='coerce');check('z_is_source_beta_over_SE',np.allclose(z,b/se,equal_nan=True));check('effect_ALT_other_REF',((d.effect_allele==d.alt)&(d.other_allele==d.ref)).all());signed=d.direction_status=='VERIFIED_SIGNED_GWAS_CONTRAST';check('signed_direction_follows_beta_sign',((d.loc[signed&(b>0),'disease_increasing_allele']==d.loc[signed&(b>0),'alt']).all() and (d.loc[signed&(b<0),'disease_increasing_allele']==d.loc[signed&(b<0),'ref']).all()));check('unresolved_rows_have_no_assigned_risk_allele',(d.loc[~signed,'disease_increasing_allele']=='').all());check('normalized_collisions_unresolved',(~signed[d.normalized_identity_duplicate]).all());check('diagnostic_gate_excludes_no_variants_based_on_provider_high_quality',np.array_equal(d.native_signed_ld_join_eligible,(d.qc_status=='SOURCE_STATISTIC_QC_PASS')&d.harmonization_status.str.startswith('VERIFIED')))
for q in l.to_dict('records'):
 g=d[d.locus_id==q['locus_id']];p=pd.to_numeric(g.pos);check(q['locus_id']+'_all_rows_inside_boundaries',((g.chrom.astype(str)==str(q['chrom']))&(p>=q['start'])&(p<=q['end'])).all());check(q['locus_id']+'_lead_present',bool((g.source_row==q['lead_source_row']).any()))
for q in d[d.normalization_changed].itertuples(index=False):
 c='chr'+str(q.chrom);left=min(q.pos,q.normalized_pos);right=max(q.pos+len(q.ref),q.normalized_pos+len(q.normalized_ref));ref=fa.fetch(c,left-1,right-1).upper();source_alt=ref[:q.pos-left]+q.alt+ref[q.pos-left+len(q.ref):];norm_alt=ref[:q.normalized_pos-left]+q.normalized_alt+ref[q.normalized_pos-left+len(q.normalized_ref):];check('normalized_haplotype_equivalence_'+str(q.source_row),source_alt==norm_alt)
check('all334_significant_source_seeds_retained',len(s)==334 and set(s.source_row).issubset(set(d.source_row)));check('single_MHC_interval_deferred',int((l.locus_status=='DEFERRED_MHC').sum())==1);check('chr20_clipped_at_GRCh37_length',int(l.loc[l.locus_id=='C_L007','end'].iloc[0])==63025520)
out={'passed':sum(x['pass'] for x in checks),'failed':sum(not x['pass'] for x in checks),'checks':checks,'completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()};(R/'output_validation.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:out[k] for k in ['passed','failed']}),flush=True)
