from pathlib import Path
import json,datetime,pandas as pd,hashlib,sys
r=Path(__file__).resolve().parents[1];o=r/'results';a=json.loads((o/'whole_file_audit.json').read_text());h=json.loads((o/'harmonization_audit.json').read_text());q=json.loads((r/'acquisition/receipt.json').read_text());du=json.loads((o/'duplicate_conflicts.json').read_text());l=pd.read_csv(o/'locus_readiness.tsv',sep='\t');ld=json.loads((o/'ld_source_contract.json').read_text())
pd.DataFrame([{'field':k,'missing_rows':v,'total_rows':a['rows'],'minimum':a['ranges'].get(k,['',''])[0],'maximum':a['ranges'].get(k,['',''])[1]} for k,v in a['missingness'].items()]).to_csv(o/'whole_file_schema_missingness.tsv',sep='\t',index=False)
pd.DataFrame([{'check':k,'failing_rows':v,'total_rows':a['rows']} for k,v in a['qc_failures'].items()]).to_csv(o/'whole_file_qc.tsv',sep='\t',index=False)
pd.DataFrame([{'check':k,**{kk:vv for kk,vv in v.items() if kk!='max_error_record'}} for k,v in a['p_consistency'].items()]).to_csv(o/'effect_test_consistency.tsv',sep='\t',index=False)
integ=[{'track':'B','file':'acquisition/hum0014.v17.COPD.v1.zip','bytes':q['bytes'],'sha256':q['sha256'],'compression':'ZIP','integrity':'PASS_ALL_MEMBERS_CRC32_AND_SIZE','scientific_scope':'Container preserved; combined-sex autosomal member only analyzed'},{'track':'B','file':'acquisition/COPD.auto.rsq07.mac10.txt.gz','bytes':q['analyzed_member']['bytes'],'sha256':q['analyzed_member']['sha256'],'compression':'GZIP','integrity':'PASS_END_TO_END_DECOMPRESSION_CRC_AND_WHOLE_FILE_SCHEMA','scientific_scope':'Combined-sex autosomal COPD'}]
pd.DataFrame(integ).to_csv(o/'complete_file_integrity.tsv',sep='\t',index=False)
acq=[]
for x in integ:acq.append(x|{'url':q['url'],'acquired_utc':q['completed_utc'],'receipt':'acquisition/receipt.json'})
for p in sorted((r/'sources').glob('*.json')):
 try:j=json.loads(p.read_text())
 except Exception:continue
 if 'url' in j:acq.append({'track':'B','file':'sources/'+p.name,'url':j['url'],'acquired_utc':j.get('completed_utc',j.get('utc',j.get('retrieved_utc',''))),'bytes':j.get('bytes',''),'sha256':j.get('sha256',''),'receipt':'sources/'+p.name,'status':j.get('status','')})
pd.DataFrame(acq).to_csv(o/'acquisition_ledger.tsv',sep='\t',index=False)
num=[]
for x in l.to_dict('records'):num.append({'track':'B','locus_id':x['locus_id'],'signed_ld_origin':'UNAVAILABLE','variant_overlap':'NOT_EVALUABLE','lead_representation':'NOT_EVALUABLE','diagonal':'NOT_RUN','symmetry':'NOT_RUN','correlation_range':'NOT_RUN','eigenvalue_PSD':'NOT_RUN','rank_conditioning':'NOT_RUN','distance_band':'NOT_RUN','variant_order':'NOT_RUN','summary_ld_residual':'NOT_RUN','state':'NOT CLEARED','blocker':'No legitimately obtained defensible dense signed Japanese LD or authorized genotype route'})
pd.DataFrame(num).to_csv(o/'ld_numerical_qc_and_summary_compatibility.tsv',sep='\t',index=False)
blockers=['Exact source score-column/software-branch lineage remains unresolved: a contemporaneous-source Tstat/varT/sqrt(MAC) reconstruction fails338/9141 sampled rows; no statistics are repaired.','Dense signed Japanese LD is not available under an established legitimate access and original pooled-cohort contract; controlled genotype/reference applications are required.','Original BBJ + ToMMo/IMM/JPHC/J-MICC representation, exact dosage/allele/order index and release must be established.','SAIGE SPA-calibrated z is not independently established as ordinary Gaussian/RSS likelihood input; compatible score-covariance/LD diagnostics and effective-sample-size design are unresolved.','All locus-level signed-LD overlap, lead completeness, PSD/rank/conditioning, boundary, and summary-LD residual diagnostics remain not run.','No complete method-ready execution input package exists for any locus.']
summary={'track':'B','accession':'GCST90013709','state':'NOT CLEARED','complete_GWAS_rows':a['rows'],'full_file_integrity':'PASS','source_signed_direction_contract':'PASS_EXPLICIT_ALT_EFFECT_APPROXIMATE_LOG_OR','prospective_loci':a['prospective_loci'],'prospective_loci_before_MHC':a['prospective_merged_loci_before_MHC'],'MHC_deferred_loci':a['mhc_deferred_loci'],'significant_valid_rows':a['significant_valid_rows'],'locus_variant_rows':a['locus_variant_rows'],'source_schema_signed_identity_pass_nonMHC_loci':h['source_schema_signed_identity_pass_nonMHC_loci'],'all_summary_statistic_gate_pass_loci':0,'LD_gate_pass_loci':0,'execution_cleared_loci':0,'loci_with_verified_signed_rows':h['loci_with_verified_signed_rows'],'valid_signed_risk_direction_rows':h['risk_direction_status'].get('VERIFIED_SIGNED_GWAS_CONTRAST_ESTIMATED_DIRECTION',0),'risk_direction_note':'Per-variant estimated disease-increasing allele; no causality or statistical-significance claim. All nonsignificant locus rows retained.','LD_source_used':'NONE','LD_blocker':ld['conclusion'],'blockers':blockers,'future_susie_execution_authorized':False,'duplicate_identity_audit':du,'artifact_paths':{'full_audit':'results/whole_file_audit.json','harmonization':'results/harmonization_audit.json','loci':'results/loci.tsv','locus_readiness':'results/locus_readiness.tsv','locus_variants':'results/locus_variants_harmonized.tsv.gz','risk_direction':'results/risk_direction.tsv.gz','LD_contract':'results/ld_source_contract.json'},'completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
(o/'audit.json').write_text(json.dumps(summary,indent=2)+'\n');pd.DataFrame([{k:v for k,v in summary.items() if isinstance(v,(str,int,float,bool))}]).to_csv(o/'track_readiness.tsv',sep='\t',index=False)
text=f'''# Track B — original BBJ combined COPD input resolution

**NOT CLEARED.** The complete signed summary file is acquired and audited, but no defensible dense signed Japanese LD source was obtained. No posterior inference, statistical fine-mapping, candidate scoring or model scoring was run.

## Complete file

Original release: [hum0014.v17.COPD.v1.zip]({q['url']}); combined-sex autosomal member `COPD.auto.rsq07.mac10.txt.gz`. Container {q['bytes']:,} bytes, SHA-256 `{q['sha256']}`. The first full response ended early; exact resume ranges, ETags and the initial failure are preserved. The completed ZIP size and every member's CRC32 pass. The combined gzip is {q['analyzed_member']['bytes']:,} bytes, SHA-256 `{q['analyzed_member']['sha256']}`; both streaming passes reached the gzip end and validated compression. Other archived chromosome-X and sex-specific files were only covered by container CRC, not scientifically analyzed.

The provider N field is variant-specific (204,905–204,907), with 11,542 rows below nominal N. The frozen source-row gate requires positive N. A coding error that initially treated nominal-N deviation as failure was corrected to that unchanged rule; the original attempt and rationale are retained in `implementation_correction.json` and its prior-attempt folder. This correction restored the chr12 locus; only the final top-level tables are authoritative.

The complete file contains **{a['rows']:,} autosomal rows** across all 22 autosomes, 20 space-delimited fields, provider hg19 coordinates. Original row order is chromosome-lexicographic, preserved by source-row identifiers; locus ordering is deterministic numeric chromosome order. Per-variant N, AF_Allele2, AF.Cases, AF.Controls, MAC, Rsq, score, SPA convergence and normal-versus-SPA P are audited. See `whole_file_schema_missingness.tsv`, `whole_file_qc.tsv` and `whole_file_audit.json` for exact missingness/ranges and all failures.

There are {a['duplicates_extra_rows']} duplicate excess rows and {a['multiallelic_positions']:,} multiple-identity source positions. The duplicated chr17:1144632 C/CT source identity has four differing rows, outside all selected loci; it is not silently collapsed. No rsID column is present: identity is build/chromosome/position/REF/ALT, never an rsID-only join.

## Signed effect and test contract

The provider defines Allele1=REF, Allele2=ALT/effect allele, BETA as effect of ALT, SE as its uncertainty, and `p.value` as the SAIGE saddlepoint P; `p.value.NA` is the normal-approximation P. The original physician-diagnosed COPD analysis includes 3,315 cases and 201,592 controls, modeled jointly using SAIGE 0.29.4.2 with age, sex and five PCs. Controls include BBJ unrelated diagnoses and ToMMo/IMM/JPHC/J-MICC population cohorts. The original study used SHAPEIT2/minimac3 with 1000 Genomes Phase3 imputation, Rsq>=0.7 and MAC>=10; that imputation source does not authorize substituting a 1KG LD matrix.

`z=BETA/SE` and both P columns are compared for every source row, with tolerances frozen before evaluation. {a['p_consistency']['p.value']['fail']:,} rows exceed the frozen P-versus-z tolerance for SPA P and {a['p_consistency']['p.value.NA']['fail']:,} for normal-approximation P. The deterministic evidence table additionally preserves every 1,000th source row plus all qualifying significant rows, spanning every chromosome and P range.

SAIGE source lineage shows that the SPA branch derives SE from its approximate log-OR and SPA P. Exact compiled v0.29.4.2 metadata is retained; adjacent and contemporaneous original source snapshots are retained with bounded version claims (`sources/saige_SOURCE_LINEAGE_NOTE.md`). Consequently, beta/SE versus SPA P agreement is expected by construction; it is not independent proof of an ordinary Gaussian likelihood. No SE, P, effect or allele is repaired to force concordance. The naive beta=Tstat/varT check is descriptive only because the SPA branch internally scales by sqrt(MAC); a source-derived branch expression is separately tested in `score_scale_sample_audit.json` and fails338/9141 sampled rows, including chr12 per-variant-N rows. This score-column lineage remains unresolved; no branch is selected merely to improve agreement. The ALT signed contrast supports estimated disease direction independently of fine-mapping readiness.

## Prospective loci and identity

The frozen candidate-blind P<5e-8, +/-1.5-Mb, transitive-merge rules produce **{a['prospective_loci']} prospective loci**, from {a['significant_valid_rows']} source-valid significant rows. No resulting merged interval intersects the conservative chr6:25–36Mb mask; no interval reaches a chromosome edge. Exact intervals and deterministic lead/source-row tie resolution are in `loci.tsv`. All nonsignificant source variants inside the intervals are retained.

Across these loci, {h['locus_rows']:,} rows were checked against the independently acquired GRCh37 reference, with {h['reference_match_rows']:,} reference matches and {h['reference_mismatch_rows']:,} mismatches. There are {h['normalization_changed_rows']:,} normalized identity changes, {h['palindromic_SNP_rows']:,} palindromic SNPs, and {h['normalized_conflict_identities']} conflicting normalized identities. No allele swap or strand flip was applied. Indels/MNVs receive explicit normalized identities while originals remain retained. Full row ledgers, excluded rows and unassessed LD coverage remain explicit.

`risk_direction.tsv.gz` assigns estimated disease-increasing alleles for {summary['valid_signed_risk_direction_rows']:,} verified signed source contrasts. This includes nonsignificant estimates and is not a claim of causal direction or statistically proven risk. No regulatory predictions are joined.

## LD and readiness

Official BBJ/NBDC resources expose controlled-access genotype routes (including original BBJ arrays and Japanese WGS imputation references). The GRCh37 BBJ7K reference has 7,472 BBJ WGS participants plus 2,504 1KG participants and is controlled access; it is not the original full COPD analysis sample. BBJ1K/2K references likewise require access and independent external-reference justification. The public ToMMo LD map is recombination distance from 96 individuals, not signed Pearson correlation; jMorp marginal frequencies cannot supply LD signs. Later PheWeb resources do not establish the original release's dense signed matrix. Exact source contracts and receipts are in `ld_source_contract.json` and `sources/`.

All **{h['loci_with_verified_signed_rows']} prospective loci contain verified signed source rows**; {h['source_schema_signed_identity_pass_nonMHC_loci']} have every original row fully resolved (symbolic/nonsequence rows remain explicit), **0 passing all summary-statistic likelihood gates**, **0 passing LD gates**, and **0 execution-cleared**. No matrix numerics or summary-LD residuals can be truthfully reported without an acquired matrix. The original mixed-model/SPA statistic covariance, sample-size design, signed matrix provenance/coverage/numerics and locus boundary compatibility remain open. All five loci retain NOT CLEARED. The independent Japanese recruitment offers a distinct ancestry track from UKB, but exact participant overlap is not inferred from labels; male/female analyses were not expanded or treated as replications.

No future SuSiE-RSS execution is authorized by this evidence. No completed execution input package is created. Investigator review is required before any statistical fine-mapping.
'''
(r/'TRACK_B_REPORT.md').write_text(text);print(json.dumps(summary,indent=2))
